/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* ADC_IRQ */
#define ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ__INTC_NUMBER 138u
#define ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ_INTC_NUMBER 138u

/* I2C_SCB_IRQ */
#define I2C_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_SCB_IRQ__INTC_NUMBER 47u
#define I2C_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_SCB_IRQ_INTC_NUMBER 47u

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* SysInt_switch */
#define SysInt_switch__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_switch__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_switch__INTC_NUMBER 0u
#define SysInt_switch_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_switch_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_switch_INTC_NUMBER 0u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
